# Generated by Django 2.1.2 on 2018-11-06 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartinfo',
            old_name='goods',
            new_name='good',
        ),
    ]
