# Generated by Django 2.1.2 on 2018-10-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=10)),
                ('upwd', models.CharField(max_length=40)),
                ('uemail', models.CharField(max_length=30)),
                ('receiver', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=80)),
                ('postalcode', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
    ]
